# This is a basic workflow to help you get started with Actions

name: Sync

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:shenhao-stu/CS224W-Fall2021.git"
          destination-repo: "git@gitee.com:shenhao-stu/CS224W-Fall2021.git"

  # reload-pages:
  #   needs: sync
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Build Gitee Pages
  #       uses: yanglbme/gitee-pages-action@main
  #       with:
  #         gitee-username: shenhao-stu
  #         gitee-password: ${{ secrets.GITEE_PASSWORD }}
  #         gitee-repo: shenhao-stu/Big-Data
  #         branch: gh-pages